source 'https://rubygems.org'

gem 'unirest'
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
gem 'http_request.rb'
gem 'builder'
gem 'spellchecker'
gem 'ffi-aspell'
gem 'goospell'
gem 'rexml-expansion-fix'
gem 'highline'
gem 'smart_colored'
gem 'jquery-rails'
